name: Check formatting with yapf

on:
  pull_request:
    branches:
      - main

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yapf
      - name: Check formatting
        run: |
          yapf -i --config yapf.cfg --diff
