name: Check linting

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check linting
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
       - name: Run ESLint
        run: |
          eslint --fix --config .eslintrc.json $(git diff --name-only HEAD)
