name: Check Code Formatting

on:
  pull_request:
    branches:
      - main

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check code formatting
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          NPM_CONFIG_NODE_MODULES_CACHE: true
        run: |
          npm install --save-dev prettier
          prettier --write --config .prettier.config.js
          prettier --check --config .prettier.config.js
